=== accessifywiki/accessifywiki-core/schema/accessibility-fixes.json
{
  "$schema": "http://json-schema.org/schema#",
  "$id": "http://nick.freear.org.uk/schemas/accessibility-fix-schema.json",

  "title": "JSON schema to specify accessibility fixes for a collection of HTML Web pages.",

  "#": "http://json.schemastore.org/package",

  "definitions": {

    "HtmlAttributeFixes": {
      "description":
        "A collection of fixes, keyed by HTML attribute name. Not an exhaustive list in 'properties' (yet?!) @TODO: See the 'white-list'.",
      "type": "object",
      "required": [],
      "additionalProperties": {
        "type": [ "string", "number", "boolean" ],
        "oneOf": [ { "type": "string" }, { "type": "number" } ]
      },
      "properties"  : {
        "alt"       : { "type": "string" },
        "aria-label": { "type": "string" },
        "maxlength" : { "type": "integer", "minimum": 1 },
        "role"      : { "type": "string" },
        "tabindex"  : { "type": "integer", "minimum": -1 },
        "title"     : { "type": "string" },
        "type"      : { "type": "string" }
      },
      "patternProperties": {
        "^aria-[a-z]{4,16}$": {
          "type": [ "string", "number", "boolean" ]
        },
        "^data-[\\w-_]+$": {
          "type": [ "string", "number", "boolean" ]
        }
      }
    },

    "AccessibilityFixStruct": {
      "type": "object",
      "required": [ "selectors" ],
      "properties"  : {
        "#"         : { "type": "string" },
        "selectors" : { "type": "string" },
        "attributes": { "$ref": "#/definitions/HtmlAttributeFixes" },
        "styles"    : {
          "type"    : "array",
          "items"   : { "type": "string" }
        }
      }
    },

    "Milliseconds": {
      "type"      : "integer",
      "minimum"   : 0,
      "maximum"   : 30000,
      "multipleOf": 10
    }

  },

  "type": "object",
  "required": [],
  "additionalProperties": false,

  "properties"  : {
    "#"         : { "type": "string" },
    "title"     : { "type": "string" },
    "updatedAt" : { "type": "string", "format": "date-time" },
    "include"   : {
      "type"    : "array",
      "items"   : { "type": "string", "format": "uri" }
    },
    "onLoadTimeout": { "$ref": "#/definitions/Milliseconds" },

    "fixesOnLoad": {
      "type"    : "array",
      "items"   : { "$ref"  : "#/definitions/AccessibilityFixStruct" }
    }
  }
}

=== accessifywiki/accessifywiki-core/tests/fixtures/example-fixes.json
{
  "title": " Accessibility fixes for the page :~ 'example.html' ",

  "updatedAt": "2020-01-26T22:30:00Z",

  "include": [ "http://localhost:9001/*" ],

  "onLoadTimeout": 200,

  "fixesOnLoad": [ {
      "#": "Just a comment ...!",
      "selectors": "img[ src *= '_Gull_' ]",
      "attributes": {
        "alt": "Photo of a black-headed gull, on :~ Species.Wikimedia.org.",
        "aria-label": "Photo of a black-headed gull, on :~ Species.Wikimedia.org."
      }
    }, {
      "selectors": ".X-i-will-not-be-found",
      "attributes": {
        "alt": "Hello world!"
      }
    }
  ]
}
